//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEquipmentControl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OfficeEquipmentControlEntities : DbContext
    {
        public OfficeEquipmentControlEntities()
            : base("name=OfficeEquipmentControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_状態> T_状態 { get; set; }
        public virtual DbSet<T_備品> T_備品 { get; set; }
        public virtual DbSet<T_備品管理> T_備品管理 { get; set; }
        public virtual DbSet<V_備品管理_MAX> V_備品管理_MAX { get; set; }
    }
}
