//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEquipmentControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_備品管理
    {
        public int 備品管理ID { get; set; }
        public int 備品ID { get; set; }
        public int 状態ID { get; set; }
        public string 利用者名 { get; set; }
        public Nullable<System.DateTime> 貸出返却日 { get; set; }
        public byte[] TS { get; set; }
        public System.DateTime 更新日 { get; set; }
        public string 更新者 { get; set; }
    
        public virtual T_状態 T_状態 { get; set; }
        public virtual T_備品 T_備品 { get; set; }
    }
}
