//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEquipmentControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_備品
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_備品()
        {
            this.T_備品管理 = new HashSet<T_備品管理>();
        }
    
        public int 備品ID { get; set; }
        public string 品名 { get; set; }
        public string 型番 { get; set; }
        public string 備考 { get; set; }
        public byte[] TS { get; set; }
        public System.DateTime 更新日 { get; set; }
        public string 更新者 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_備品管理> T_備品管理 { get; set; }
    }
}
