//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEquipmentControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_備品管理_MAX
    {
        public Nullable<int> 備品管理ID { get; set; }
        public string 品名 { get; set; }
        public int 備品ID { get; set; }
        public string 型番 { get; set; }
        public string 備考 { get; set; }
        public string 利用者名 { get; set; }
        public Nullable<System.DateTime> 貸出返却日 { get; set; }
        public int 状態ID { get; set; }
        public string 状態 { get; set; }
        public string QRCodeURL { get; set; }
        public Nullable<int> Next状態 { get; set; }
        public string Next状態String { get; set; }
    }
}
